[versions]
kotlin-inject = "0.5.2-SNAPSHOT"
kotlin = "1.7.0"
ksp = "1.7.0-1.0.6"
kotlinpoet = "1.12.0"
junit5 = "5.8.1"
detekt = "1.19.0"
[libraries]
kotiln-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-compile-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version = "1.4.5" }
room-compiler-processing-testing = { module = "androidx.room:room-compiler-processing-testing", version = "2.4.0" }
kotlin-annotation-processing-embeddable = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-embeddable", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.3" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version = "0.5.0" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version = "0.18.2" }
jdk-compiler = { module = "io.earcam.wrapped:jdk.compiler", version = "1.8.132" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.25" }
burst-junit4 = { module = "com.squareup.burst:burst-junit4", version = "1.2.0" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
javax-inject = { module = "javax.inject:javax.inject", version = "1" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
[bundles]
kotlin-compile-testing = [
# switching to room-compiler-processing-testing for now because of https://github.com/tschuchortdev/kotlin-compile-testing/issues/72
#     "kotlin-compile-testing",
#     "kotlin-annotation-processing-embeddable",
    "ksp",
    "room-compiler-processing-testing"
]
kotlin-test-junit5 = ["junit5-api", "junit5-params", "kotlin-reflect"]
[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
jmh = { id = "me.champeau.jmh", version = "0.6.6" }
