[versions]
kotlin-inject = "0.7.3-SNAPSHOT"
kotlin = "2.0.10"
ksp = "2.0.10-1.0.24"
kotlinpoet = "2.0.0"
junit5 = "5.9.3"
jvmTarget = "11"
detekt = "1.23.6"
[libraries]
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:ksp", version = "0.4.1" }
kotlin-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.8.0" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version = "0.23.2" }
jdk-compiler = { module = "io.earcam.wrapped:jdk.compiler", version = "1.8.132" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.0" }
burst-junit4 = { module = "com.squareup.burst:burst-junit4", version = "1.2.0" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
javax-inject = { module = "javax.inject:javax.inject", version = "1" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

[bundles]
kotlin-compile-testing = [
    "kotlin-compile-testing",
    "ksp",
]
kotlin-test-junit5 = ["junit5-api", "junit5-params", "kotlin-reflect"]
[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
jmh = { id = "me.champeau.jmh", version = "0.6.6" }
